[2022-11-14 12:39:48,946] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-正例接口测试开始----------------
[2022-11-14 12:39:48,947] logger_utils.py->print_log line:20 [INFO]请求方式：get
[2022-11-14 12:39:48,948] logger_utils.py->print_log line:20 [INFO]请求地址：https://api.weixin.qq.com/cgi-bin/token
[2022-11-14 12:39:48,948] logger_utils.py->print_log line:20 [INFO]请求params参数：{'grant_type': 'client_credential', 'appid': 'wxf393fadf3268a5d5', 'secret': 'e9a29dfa3920020ebee3675bcc9c2cf8'}
[2022-11-14 12:39:49,245] logger_utils.py->print_log line:20 [INFO]预期结果：[{'codes': {'status_code': 200}}, {'contains': 'access_token'}]
[2022-11-14 12:39:49,245] logger_utils.py->print_log line:20 [INFO]实际结果：{'access_token': '62_1iJOMc65M3f-Yfv6tZr9Wa9ID0CqVJO8R6n78krKxS1qKUjSyl8VZ53MYGodJ5yXoKvTAZwL0ICRNKk4IrCYW-ymcZpHI3ib_wcVRo9uSMDauOO3O5ODccpCVXIQEXhACADRK', 'expires_in': 7200},status_code:200
[2022-11-14 12:39:49,245] logger_utils.py->print_log line:20 [INFO]状态码断言
[2022-11-14 12:39:49,246] logger_utils.py->print_log line:20 [INFO]包含断言
[2022-11-14 12:39:49,246] logger_utils.py->print_log line:20 [INFO]获取鉴权码-正例业务断言成功
[2022-11-14 12:39:49,246] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-正例接口测试结束----------------

[2022-11-14 12:39:49,254] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-appid为空接口测试开始----------------
[2022-11-14 12:39:49,254] logger_utils.py->print_log line:20 [INFO]请求方式：get
[2022-11-14 12:39:49,255] logger_utils.py->print_log line:20 [INFO]请求地址：https://api.weixin.qq.com/cgi-bin/token
[2022-11-14 12:39:49,255] logger_utils.py->print_log line:20 [INFO]请求params参数：{'grant_type': 'client_credential', 'appid': '', 'secret': 'e9a29dfa3920020ebee3675bcc9c2cf8'}
[2022-11-14 12:39:49,294] logger_utils.py->print_log line:20 [INFO]正则表达式"access_token":"(.*?)"可能有误，或者(反例)接口请求失败，未提取到中间变量
[2022-11-14 12:39:49,294] logger_utils.py->print_log line:20 [INFO]jsonpath表达式$..expires_in可能有误，或者(反例)接口请求失败，未提取到中间变量
[2022-11-14 12:39:49,294] logger_utils.py->print_log line:20 [INFO]预期结果：[{'codes': {'status_code': 200}}, {'contains': '41002'}]
[2022-11-14 12:39:49,294] logger_utils.py->print_log line:20 [INFO]实际结果：{'errcode': 41002, 'errmsg': 'appid missing rid: 6371c694-14ba80e2-784adfae'},status_code:200
[2022-11-14 12:39:49,295] logger_utils.py->print_log line:20 [INFO]状态码断言
[2022-11-14 12:39:49,295] logger_utils.py->print_log line:20 [INFO]包含断言
[2022-11-14 12:39:49,295] logger_utils.py->print_log line:20 [INFO]获取鉴权码-appid为空业务断言成功
[2022-11-14 12:39:49,295] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-appid为空接口测试结束----------------

[2022-11-14 12:39:49,302] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-secret为空接口测试开始----------------
[2022-11-14 12:39:49,303] logger_utils.py->print_log line:20 [INFO]请求方式：get
[2022-11-14 12:39:49,303] logger_utils.py->print_log line:20 [INFO]请求地址：https://api.weixin.qq.com/cgi-bin/token
[2022-11-14 12:39:49,304] logger_utils.py->print_log line:20 [INFO]请求params参数：{'grant_type': 'client_credential', 'appid': 'wxf393fadf3268a5d5', 'secret': ''}
[2022-11-14 12:39:49,377] logger_utils.py->print_log line:20 [INFO]正则表达式"access_token":"(.*?)"可能有误，或者(反例)接口请求失败，未提取到中间变量
[2022-11-14 12:39:49,377] logger_utils.py->print_log line:20 [INFO]jsonpath表达式$..expires_in可能有误，或者(反例)接口请求失败，未提取到中间变量
[2022-11-14 12:39:49,377] logger_utils.py->print_log line:20 [INFO]预期结果：[{'codes': {'status_code': 200}}, {'contains': '41004'}]
[2022-11-14 12:39:49,378] logger_utils.py->print_log line:20 [INFO]实际结果：{'errcode': 41004, 'errmsg': 'appsecret missing rid: 6371c694-08a27d9f-11d9b7ea'},status_code:200
[2022-11-14 12:39:49,378] logger_utils.py->print_log line:20 [INFO]状态码断言
[2022-11-14 12:39:49,378] logger_utils.py->print_log line:20 [INFO]包含断言
[2022-11-14 12:39:49,378] logger_utils.py->print_log line:20 [INFO]获取鉴权码-secret为空业务断言成功
[2022-11-14 12:39:49,378] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-secret为空接口测试结束----------------

[2022-11-14 12:39:49,386] logger_utils.py->print_log line:20 [INFO]----------------选择标签-正常接口测试开始----------------
[2022-11-14 12:39:49,392] logger_utils.py->error_log line:15 [ERROR]requests_utils模块standard_yaml_testcase方法报错：Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 35, in standard_yaml_testcase
    for i, j in caseinfo['request']['params'].items():
                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'params'

