[2022-11-14 13:15:33,112] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-正例接口测试开始----------------
[2022-11-14 13:15:33,113] logger_utils.py->print_log line:20 [INFO]请求方式：get
[2022-11-14 13:15:33,113] logger_utils.py->print_log line:20 [INFO]请求地址：https://api.weixin.qq.com/cgi-bin/token
[2022-11-14 13:15:33,114] logger_utils.py->print_log line:20 [INFO]请求params参数：{'grant_type': 'client_credential', 'appid': 'wxf393fadf3268a5d5', 'secret': 'e9a29dfa3920020ebee3675bcc9c2cf8'}
[2022-11-14 13:15:33,402] logger_utils.py->print_log line:20 [INFO]extract配置参数为空，请检查
[2022-11-14 13:15:33,402] logger_utils.py->print_log line:20 [INFO]预期结果：[{'codes': {'status_code': 200}}, {'contains': 'access_token'}]
[2022-11-14 13:15:33,403] logger_utils.py->print_log line:20 [INFO]实际结果：{'access_token': '62_a4Qozzx4RYusELN3EM6kAUyW__GtzLy2iLWYG2fBIwfokoC7HMQX5cfsdSFWH1uDNREe6s-xNfGELvtuXxAS3PS8IIwP1AfaIF2SpLWCeHch7AAv7E6mR-LPNSkYVIbAJAJGT', 'expires_in': 7200},status_code:200
[2022-11-14 13:15:33,403] logger_utils.py->print_log line:20 [INFO]状态码断言
[2022-11-14 13:15:33,403] logger_utils.py->print_log line:20 [INFO]包含断言
[2022-11-14 13:15:33,403] logger_utils.py->print_log line:20 [INFO]获取鉴权码-正例业务断言成功
[2022-11-14 13:15:33,403] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-正例接口测试结束----------------

[2022-11-14 13:15:33,413] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-appid为空接口测试开始----------------
[2022-11-14 13:15:33,413] logger_utils.py->print_log line:20 [INFO]请求方式：get
[2022-11-14 13:15:33,414] logger_utils.py->print_log line:20 [INFO]请求地址：https://api.weixin.qq.com/cgi-bin/token
[2022-11-14 13:15:33,415] logger_utils.py->print_log line:20 [INFO]请求params参数：{'grant_type': 'client_credential', 'appid': '', 'secret': 'e9a29dfa3920020ebee3675bcc9c2cf8'}
[2022-11-14 13:15:33,458] logger_utils.py->print_log line:20 [INFO]extract配置参数为空，请检查
[2022-11-14 13:15:33,459] logger_utils.py->print_log line:20 [INFO]预期结果：[{'codes': {'status_code': 200}}, {'contains': '41002'}]
[2022-11-14 13:15:33,459] logger_utils.py->print_log line:20 [INFO]实际结果：{'errcode': 41002, 'errmsg': 'appid missing rid: 6371cef4-1d81f198-0d6b56e8'},status_code:200
[2022-11-14 13:15:33,459] logger_utils.py->print_log line:20 [INFO]状态码断言
[2022-11-14 13:15:33,459] logger_utils.py->print_log line:20 [INFO]包含断言
[2022-11-14 13:15:33,459] logger_utils.py->print_log line:20 [INFO]获取鉴权码-appid为空业务断言成功
[2022-11-14 13:15:33,460] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-appid为空接口测试结束----------------

[2022-11-14 13:15:33,468] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-secret为空接口测试开始----------------
[2022-11-14 13:15:33,468] logger_utils.py->print_log line:20 [INFO]请求方式：get
[2022-11-14 13:15:33,469] logger_utils.py->print_log line:20 [INFO]请求地址：https://api.weixin.qq.com/cgi-bin/token
[2022-11-14 13:15:33,469] logger_utils.py->print_log line:20 [INFO]请求params参数：{'grant_type': 'client_credential', 'appid': 'wxf393fadf3268a5d5', 'secret': ''}
[2022-11-14 13:15:33,546] logger_utils.py->print_log line:20 [INFO]extract配置参数为空，请检查
[2022-11-14 13:15:33,547] logger_utils.py->print_log line:20 [INFO]预期结果：[{'codes': {'status_code': 200}}, {'contains': '41004'}]
[2022-11-14 13:15:33,547] logger_utils.py->print_log line:20 [INFO]实际结果：{'errcode': 41004, 'errmsg': 'appsecret missing rid: 6371cef4-4a75bacc-5c54bbb7'},status_code:200
[2022-11-14 13:15:33,547] logger_utils.py->print_log line:20 [INFO]状态码断言
[2022-11-14 13:15:33,547] logger_utils.py->print_log line:20 [INFO]包含断言
[2022-11-14 13:15:33,547] logger_utils.py->print_log line:20 [INFO]获取鉴权码-secret为空业务断言成功
[2022-11-14 13:15:33,547] logger_utils.py->print_log line:20 [INFO]----------------获取鉴权码-secret为空接口测试结束----------------

[2022-11-14 13:15:33,554] logger_utils.py->print_log line:20 [INFO]----------------文件上传接口测试开始----------------
[2022-11-14 13:15:33,554] logger_utils.py->print_log line:20 [INFO]headers没有value,请确认
[2022-11-14 13:15:33,554] logger_utils.py->print_log line:20 [INFO]json没有value,请确认
[2022-11-14 13:15:33,554] logger_utils.py->print_log line:20 [INFO]请求方式：post
[2022-11-14 13:15:33,555] logger_utils.py->print_log line:20 [INFO]请求地址：https://api.weixin.qq.com/cgi-bin/media/uploadimg
[2022-11-14 13:15:33,555] logger_utils.py->print_log line:20 [INFO]headers未填充，或者(反例)设计为空
[2022-11-14 13:15:33,557] logger_utils.py->error_log line:15 [ERROR]requests_utils模块replace_get_value方法报错：Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 150, in replace_get_value
    new_value = getattr(DebugTalk(), function_name)(*all_args_value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ms-jiekou\hotloads\debug_talk.py", line 17, in read_extract
    return result[key]
           ~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable

[2022-11-14 13:15:33,559] logger_utils.py->error_log line:15 [ERROR]requests_utils模块send_all_request方法报错：Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 150, in replace_get_value
    new_value = getattr(DebugTalk(), function_name)(*all_args_value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ms-jiekou\hotloads\debug_talk.py", line 17, in read_extract
    return result[key]
           ~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 108, in send_all_request
    kwargs[key] = self.replace_get_value(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 165, in replace_get_value
    error_log("requests_utils模块replace_get_value方法报错：%s" % str(traceback.format_exc()))
  File "D:\Python_project\ms-jiekou\commons\logger_utils.py", line 16, in error_log
    raise AssertionError(message)
AssertionError: requests_utils模块replace_get_value方法报错：Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 150, in replace_get_value
    new_value = getattr(DebugTalk(), function_name)(*all_args_value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ms-jiekou\hotloads\debug_talk.py", line 17, in read_extract
    return result[key]
           ~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable


[2022-11-14 13:15:33,560] logger_utils.py->error_log line:15 [ERROR]requests_utils模块standard_yaml_testcase方法报错：Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 150, in replace_get_value
    new_value = getattr(DebugTalk(), function_name)(*all_args_value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ms-jiekou\hotloads\debug_talk.py", line 17, in read_extract
    return result[key]
           ~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 108, in send_all_request
    kwargs[key] = self.replace_get_value(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 165, in replace_get_value
    error_log("requests_utils模块replace_get_value方法报错：%s" % str(traceback.format_exc()))
  File "D:\Python_project\ms-jiekou\commons\logger_utils.py", line 16, in error_log
    raise AssertionError(message)
AssertionError: requests_utils模块replace_get_value方法报错：Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 150, in replace_get_value
    new_value = getattr(DebugTalk(), function_name)(*all_args_value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ms-jiekou\hotloads\debug_talk.py", line 17, in read_extract
    return result[key]
           ~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 45, in standard_yaml_testcase
    res = self.send_all_request(method, url, base_url, **caseinfo['request'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 117, in send_all_request
    error_log("requests_utils模块send_all_request方法报错：%s" % str(traceback.format_exc()))
  File "D:\Python_project\ms-jiekou\commons\logger_utils.py", line 16, in error_log
    raise AssertionError(message)
AssertionError: requests_utils模块send_all_request方法报错：Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 150, in replace_get_value
    new_value = getattr(DebugTalk(), function_name)(*all_args_value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ms-jiekou\hotloads\debug_talk.py", line 17, in read_extract
    return result[key]
           ~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 108, in send_all_request
    kwargs[key] = self.replace_get_value(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 165, in replace_get_value
    error_log("requests_utils模块replace_get_value方法报错：%s" % str(traceback.format_exc()))
  File "D:\Python_project\ms-jiekou\commons\logger_utils.py", line 16, in error_log
    raise AssertionError(message)
AssertionError: requests_utils模块replace_get_value方法报错：Traceback (most recent call last):
  File "D:\Python_project\ms-jiekou\commons\requests_util.py", line 150, in replace_get_value
    new_value = getattr(DebugTalk(), function_name)(*all_args_value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_project\ms-jiekou\hotloads\debug_talk.py", line 17, in read_extract
    return result[key]
           ~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable



